@root-URL = http://localhost:8001
@user-API = {{root-URL}}/library/users
@book-API = {{root-URL}}/library/books
### 
POST {{user-API}}/login
Content-Type: application/json

{
    "email":"jon@gmail.com",
    "password":123
}

### 
POST {{user-API}}/signup
Content-Type: application/json

{
    "firstName":"Jon",
    "lastName":"Doe",
    "phone":123456,
    "email":"jon@gmail.com",
    "password":"123"
}

###
GET {{root-URL}}
###
POST {{user-API}}/login
###
POST {{user-API}}/signup

### 
GET {{user-API}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzE2MjU3NDIxLCJleHAiOjE3MTYyNTgzMjF9.hb2xevCo8LWeWMg-o5g3-CMc19cpSPStgt4J5o24p7k